### ISSUE TITLE
Setup Project

### ISSUE THREAD

**Issue by cananozyol** [cananozyol/read-and-meet-capstone-project#2]
---

about: Steps to set up the project

---

# Tasks

- [x] create wireframes in miro to visualize the different frontend views
- [x] write userstories
- [x] create UML digramm
- [x] create project in IDE
- [x] add backend
- [x] add frontend
- [x] add CI
- [x] add gitignore
- [x] add CD

# Complexity
20

#

![Image](https://user-images.githubusercontent.com/135017917/255530838-df5e0874-c71e-46fe-815e-b1e7f57d4786.png)
